### PR TITLE
Solved validation bug 

### LINKED ISSUE #69: Bug during validation
```
500
Internal Server Error
Last unit does not have enough valid bits
```

Setup: on a challenge already validated (including comment and image), modify the comment but not the image and then validate. It looks like validating a previously posted image triggers this error.

Edit: the line 114 of `CompletedService` in method `addCompletedChallenge` triggers the exception. This is because the second time we are posting the image path and not the base64 value. Solution: overload the method with another using only the imgPath ?

### PR DESCRIPTION
**Pull request by JulienVig**
If an image has already been posted, validated again without modifying the image triggers an internal error since the base64 value is null.
Resolved bug by not sending the image if not modified 

Closes #69

### CODE REVIEW

File: front/components/ValidationMain.js [hunk 1]
```diff
@@ -119,12 +119,13 @@ export default class ImagePickerExample extends React.Component {
 
   //Post the comment and the image base64 
   _submitValidation = async () => {
+    console.log(this.state.image.base64 == null)
```
Comment (JulienVig) [inline front/components/ValidationMain.js:122]:
```suggestion
```
